"""initial migration

Revision ID: c272364f87a
Revises: None
Create Date: 2015-08-12 15:41:02.899292

"""

# revision identifiers, used by Alembic.
revision = 'c272364f87a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archive_title', sa.Unicode(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('archive_title')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_name')
    )
    op.create_table('tags_archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('archive_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_archives_archive_id'), 'tags_archives', ['archive_id'], unique=False)
    op.create_index(op.f('ix_tags_archives_tag_id'), 'tags_archives', ['tag_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_archives_tag_id'), table_name='tags_archives')
    op.drop_index(op.f('ix_tags_archives_archive_id'), table_name='tags_archives')
    op.drop_table('tags_archives')
    op.drop_table('tags')
    op.drop_table('archives')
    ### end Alembic commands ###
